title: shellz.club
description: "Penetration Tester and Red Team Operator. I enjoy security related research and discussion."
baseurl: ""
url: "https://new.shellz.club"

theme: minima

minima:
  skin: auto
